### ISSUE TITLE
Failed Scans - after pokemon learn new skill/evolve

### ISSUE THREAD

**Issue by ofir-mev** [ssjshields/archetype-counter#26]
so I got a weird a bug when my pokemon learn new skill or evolve the counter try to count the battle again(busy status)
and when its doing it its catching names of the players near me and i get an error.

[DEBUG_OCR_OUTPUT.txt](https://github.com/ssjshields/archetype-counter/files/12588458/DEBUG_OCR_OUTPUT.txt)
![ArchetypeScreenshot](https://github.com/ssjshields/archetype-counter/assets/57320827/fc2a50e7-045b-4bba-bb55-c47f71456a6d)
![ArchetypeScreenshotEncounter](https://github.com/ssjshields/archetype-counter/assets/57320827/46a7bcc0-1728-499e-bd7e-e5c6eaeb673f)
![ArchetypeScreenshotMagick](https://github.com/ssjshields/archetype-counter/assets/57320827/668e1025-b010-4674-a6ef-b37cec84047c)

**Comment by ssjshields** [comment]
Noted, similar to https://github.com/ssjshields/archetype-counter/issues/21. 

Evolving or move learn seems to trick the Counter into thinking its in a battle, and then since the player names are kind of similar to monster names, you can see in the picture they get scanned and attempt to process. @AnonymousPoke is aware of this, I believe this should occur less or be entirely fixed in the next few updates that will be coming out soon.

**Comment by ofir-mev** [comment]
ok thank u

**Comment by AnonymousPoke** [comment]
@ofir-mev, I have not been able to reproduce this issue at will, but please download the latest main build and see if you receive the issue further.

**Comment by ofir-mev** [comment]
> @ofir-mev, I have not been able to reproduce this issue at will, but please download the latest main build and see if you receive the issue further.

still happening.
my pokemon evolve the counter go to the busy status again I canceled the evolve and I get the error

**Comment by AnonymousPoke** [comment]
duplicate issue from https://github.com/ssjshields/archetype-counter/issues/34
